# Generated by Django 2.2 on 2020-03-17 06:19

import dap_booking.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='profile_pictures/default_profile_picture.jpg', upload_to='profile_pictures')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=100)),
                ('package_display_picture', models.ImageField(default='package_display_pictures/default_package_picture.jpg', upload_to='package_display_pictures')),
                ('num_days', models.IntegerField()),
                ('num_countries', models.IntegerField()),
                ('num_cities', models.IntegerField()),
                ('description', models.TextField(max_length=400)),
                ('price', models.FloatField()),
                ('discounted_price', models.FloatField(blank=True, null=True)),
                ('travel_outbound_flight_date', models.DateField(default=django.utils.timezone.now)),
                ('travel_inbound_flight_date', models.DateField(default=dap_booking.models.return_flight)),
                ('inclusions', models.TextField(max_length=500)),
                ('exclusions', models.TextField(max_length=500)),
                ('terms_and_conditions', models.TextField(max_length=500)),
                ('tag', models.CharField(blank=True, choices=[('New', 'New'), ('Hot', 'Hot')], default='New', max_length=10)),
                ('package_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
