# Generated by Django 2.2 on 2020-03-22 11:56

import dap_booking.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=100)),
                ('package_display_picture', models.ImageField(default='package_display_pictures/default_package_picture.jpg', upload_to='package_display_pictures')),
                ('num_days', models.IntegerField()),
                ('num_countries', models.IntegerField()),
                ('num_cities', models.IntegerField()),
                ('description', models.TextField(max_length=400)),
                ('price', models.FloatField()),
                ('discounted_price', models.FloatField(blank=True, null=True)),
                ('travel_outbound_flight_date', models.DateField(default=django.utils.timezone.now)),
                ('travel_inbound_flight_date', models.DateField(default=dap_booking.models.return_flight)),
                ('inclusions', models.TextField(max_length=500)),
                ('exclusions', models.TextField(max_length=500)),
                ('terms_and_conditions', models.TextField(max_length=500)),
                ('tag', models.CharField(blank=True, choices=[('New', 'New'), ('Hot', 'Hot')], default='New', max_length=10)),
                ('package_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='profile_pictures/default_profile_picture.jpg', upload_to='profile_pictures')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('proof_of_payment', models.ImageField(blank=True, upload_to='proof_of_payment')),
                ('proof_of_payment_deadline', models.DateTimeField(default=dap_booking.models.deadline)),
                ('proof_of_payment_status', models.BooleanField(default=False, verbose_name='Verified')),
                ('is_overdue', models.BooleanField(default=False, verbose_name='Overdue')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Finished')),
                ('flight_ticket', models.FileField(blank=True, upload_to='flight_tickets')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dap_booking.Package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_initial', models.CharField(max_length=5)),
                ('birthday', models.DateField(default=django.utils.timezone.now)),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F')], default='M', max_length=1)),
                ('contact_number', models.CharField(max_length=30)),
                ('email_address', models.CharField(max_length=100)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dap_booking.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='CustomPackageRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(default='My Custom Package', max_length=100)),
                ('budget', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('flight_ticket', models.BooleanField(blank=True, default=False)),
                ('origin', models.CharField(blank=True, max_length=100)),
                ('destination', models.CharField(blank=True, max_length=100)),
                ('travel_outbound_flight_date', models.DateField(default=django.utils.timezone.now)),
                ('travel_inbound_flight_date', models.DateField(default=django.utils.timezone.now)),
                ('hotel_accomodation', models.BooleanField(blank=True, default=False)),
                ('travel_voucher', models.BooleanField(blank=True, default=False)),
                ('travel_insurance', models.BooleanField(blank=True, default=False)),
                ('additional_notes', models.TextField(blank=True, max_length=500, verbose_name='Additional Notes / Special Requests')),
                ('contact_person', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=30)),
                ('email_address', models.CharField(max_length=100)),
                ('preferred_date', models.DateField(default=django.utils.timezone.now)),
                ('preferred_time', models.TimeField(default=django.utils.timezone.now)),
                ('request_status', models.CharField(choices=[('Approved', 'Approved'), ('Processing', 'Processing')], default='Processing', max_length=50)),
                ('booking_status', models.CharField(choices=[('Booked', 'Booked'), ('Pending', 'Pending')], default='Pending', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
