# Generated by Django 2.2 on 2020-03-22 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dap_booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custompackagerequest',
            options={'verbose_name': 'Custom Package Requests'},
        ),
    ]
