# Generated by Django 2.2 on 2020-03-17 12:27

import dap_booking.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dap_booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('proof_of_payment', models.ImageField(blank=True, upload_to='proof_of_payment')),
                ('proof_of_payment_deadline', models.DateTimeField(default=dap_booking.models.deadline)),
                ('proof_of_payment_status', models.BooleanField(default=False, verbose_name='Verified')),
                ('is_overdue', models.BooleanField(default=False, verbose_name='Overdue')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Finished')),
                ('flight_ticket', models.FileField(blank=True, upload_to='flight_tickets')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dap_booking.Package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
