# Generated by Django 2.2 on 2020-03-22 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dap_booking', '0002_auto_20200322_2021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custompackagerequest',
            options={'verbose_name': 'Custom Package Request'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile'},
        ),
    ]
