# Generated by Django 2.2 on 2020-03-20 00:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dap_booking', '0003_passenger'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPackageRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(default='My Custom Package', max_length=100)),
                ('budget', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('flight_ticket', models.BooleanField(blank=True, default=False)),
                ('origin', models.CharField(blank=True, max_length=100)),
                ('destination', models.CharField(blank=True, max_length=100)),
                ('travel_outbound_flight_date', models.DateField(default=django.utils.timezone.now)),
                ('travel_inbound_flight_date', models.DateField(default=django.utils.timezone.now)),
                ('hotel', models.BooleanField(blank=True, default=False)),
                ('travel_voucher', models.BooleanField(blank=True, default=False)),
                ('travel_insurance', models.BooleanField(blank=True, default=False)),
                ('additional_notes', models.TextField(blank=True, max_length=500, verbose_name='Additional Notes / Special Requests')),
                ('contact_person', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=30)),
                ('email_address', models.CharField(max_length=100)),
                ('preferred_date', models.DateField(default=django.utils.timezone.now)),
                ('preferred_time', models.TimeField(default=django.utils.timezone.now)),
                ('request_status', models.CharField(choices=[('Approved', 'Approved'), ('Processing', 'Processing')], default='Processing', max_length=50)),
                ('booking_status', models.CharField(choices=[('Booked', 'Booked'), ('Pending', 'Pending')], default='Pending', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
